/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.groupthree.food_project.views;

import com.groupthree.food_project.dao.OrderDetailDAO;
import com.groupthree.food_project.dao.UsersDAO;
import com.groupthree.food_project.models.OrderDetail;
import java.util.List;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alone
 */
public class MyOrder extends javax.swing.JFrame {
    /**
     * Creates new form MyOrder
     */
    public MyOrder() {
        initComponents();
        int userId = UsersDAO.currentUser.getUserId();
        loadOrderList(userId);

        // Thêm sự kiện khi chọn orderId từ ComboBox
        OrderList.addActionListener(e -> {
            String selectedOrder = (String) OrderList.getSelectedItem();
            if (selectedOrder != null) {
                int orderId = Integer.parseInt(selectedOrder);
                loadOrderDetails(orderId);
            }
        });
        if (OrderList.getItemCount() > 0) {
            int firstOrderId = Integer.parseInt(OrderList.getItemAt(0));
            loadOrderDetails(firstOrderId);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OrderList = new javax.swing.JComboBox<>();
        status = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        OrderList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OrderList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đơn hàng", " " }));
        OrderList.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        OrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderListActionPerformed(evt);
            }
        });

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setText("Trạng thái:");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Món ăn", "Số lượng", "Giá tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderTable);

        total.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        total.setText("Thành tiền:");

        CancelButton.setBackground(new java.awt.Color(0, 0, 0));
        CancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelButton.setText("Huỷ đơn");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(OrderList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(status)
                .addGap(76, 76, 76))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total)
                    .addComponent(CancelButton))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Lấy orderId từ danh sách
        String selectedOrder = (String) OrderList.getSelectedItem();
        if (selectedOrder == null) {
            return;
        }

        int orderId = Integer.parseInt(selectedOrder);

        // Kiểm tra trạng thái đơn hàng
        String orderStatus = OrderDetailDAO.getOrderStatus(orderId);

        if ("Đã hủy".equals(orderStatus)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Đơn hàng đã bị hủy trước đó!", "Thông báo",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Xác nhận từ người dùng
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn hủy đơn hàng này?",
                "Xác nhận hủy", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        // Cập nhật trạng thái đơn hàng thành "Đã hủy"
        boolean success = OrderDetailDAO.cancelOrder(orderId);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Hủy đơn hàng thành công!", "Thành công",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // 🟢 Cập nhật trạng thái trên giao diện
            status.setText("Trạng thái: Đã hủy");

            // 🟢 Cập nhật tổng tiền về 0
            total.setText("Thành tiền: 0 VND");

            // 🟢 Xóa dữ liệu trong bảng
            DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
            model.setRowCount(0);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Hủy đơn hàng thất bại!", "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // GEN-LAST:event_CancelButtonActionPerformed

    private void OrderListActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_OrderListActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_OrderListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyOrder().setVisible(true);
            }
        });
    }
    public void refreshOrderList() {
        int userId = UsersDAO.currentUser.getUserId(); // Lấy ID người dùng hiện tại
        loadOrderList(userId); // Tải lại danh sách đơn hàng
    }

    private void loadOrderDetails(int orderId) {
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        double sum = 0;

        List<OrderDetail> orderDetails = OrderDetailDAO.getOrderDetailsByOrderId(orderId);
        for (OrderDetail detail : orderDetails) {
            model.addRow(new Object[] {
                    detail.getProductName(), // Hiển thị tên món ăn
                    detail.getQuantity(), // Hiển thị số lượng
                    detail.getUnitPrice() // Hiển thị giá tiền
            });
            sum+=detail.getQuantity()*detail.getUnitPrice();
        }
        total.setText("Tổng tiền " + sum);
        status.setText("Trạng thái "+OrderDetailDAO.getOrderStatus(orderId));
    }

    private void loadOrderList(int userId) {
        OrderList.removeAllItems(); // Xóa danh sách cũ
        List<Integer> orderIds = OrderDetailDAO.getOrderIds(userId); // Lấy danh sách orderId của user

        for (Integer orderId : orderIds) {
            OrderList.addItem(String.valueOf(orderId)); // Thêm orderId vào ComboBox
        }

        // Nếu có ít nhất một đơn hàng, hiển thị chi tiết đơn đầu tiên
        if (OrderList.getItemCount() > 0) {
            loadOrderDetails(Integer.parseInt(OrderList.getItemAt(0)));
        }

        // Thêm sự kiện khi chọn order khác
        OrderList.addActionListener(e -> {
            String selectedOrder = (String) OrderList.getSelectedItem();
            if (selectedOrder != null) {
                int orderId = Integer.parseInt(selectedOrder); // Đúng cách
                loadOrderDetails(orderId);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> OrderList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel status;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
